### ISSUE TITLE
Dependency list

### ISSUE THREAD

**Issue by jonblack** [mhekkel/libzeep#3]
Looking in the makefile I can see which libraries are required, but not the version. Which versions of the libraries are required?

**Comment by mhekkel** [comment]
I try to keep that flexible although I know that's not the answer you're looking for.

A related problem here is that for building a modern C++ program you will probably want to use c++11 features. And in order to use these, you will have to build your boost libraries yourself using the correct flags and a recent compiler.

I'm currently using boost 1.56 to build libzeep which is already quite out of date.
